//
//  Data.swift
//  Rezepte
//
//  Created by Natalie Wolf on 26.09.20.
//
import SwiftUI

struct Recipe: Hashable, Encodable, Identifiable {
    var id : String
    let title: String
    let subtitle: String
    let category: String
    let time: String
    let description: String
    let image: String
    //var favourited: Bool
}

struct Data {
    static let recipes = [
        Recipe(id: "0", title:"Zimt Pancakes", subtitle: "Mit Äpfeln, Walnüssen und Erdnussbutter", category: "Amerikanisch", time: "20 Min.", description: "Zunächst ein Ei gmeinsam mit 90 ml Milch, einem Esslöffel flüssigem Kokosöl und ein bis zwei Esslöffel Zucker schumig mixen. Anschließend  40 ml Mineralwasser hinzugeben, damit die Kohlensäure enthalten bleibt. In einer Schüssel 75 g Mehl, einem Teelöffel Zimt und einem Teelöffel Backpulver zunächst separat vermischen und dann zu Milchmischung geben. Alles kurz und schnell mixen. Der Teil sollte eine cremige und dickflüssige Konsistenz haben. Den Teig dann ca. 10 Minuten stehen lassen. Kokosöl in einer großen Pfanne auf mittlerer Stufe erhitzen. Nun ca. zwei Teelöffel Teil pro Pancake in die Pafanne geben und mit einer kreisenden Bewegung runde Pancakes formen. Sobald sich oben Bläschen bilden, die Pfannkuchen werden und für weitere zwei bis drei Minuten zuende backen. Die warmen Pankakes mit Erdnussbutter, Äpfeln und Walnüssen servieren.", image: "Bananenbrot"),
        Recipe(id: "1",title:"Baguettes", subtitle: "Den französischen Brotklassier selbst machen.", category: "Französisch", time: "55 Min.", description: "400 g Mehl,  eineinhalb Teelöffel Salz und eine Prise Zucker in einer Schüssel vermischen. Ein viertel Würfel frische Hefe hinein bröckeln. 270ml lauwarmes Wasser zugeben. Alles verkneten, bis kein Mehl mehr zu sehen ist. Den Teig zugedeckt 2 Std. ruhen lassen. Teig auf eine stark bemehlte Arbeitsfläche schütten und mit Hilfe einer Teigkarte oder einem Messer in zwei Teile halbieren. Jedes Teigstück mit den Händen zu einem ca. 40 cm langen Strang formen und auf ein mit Backpapier belegtes Backblech legen. Mit etwas Mehl bestäuben und zugedeckt ruhen lassen bis der Ofen auf 230 Grad (Umluft: 210 Grad) vorgeheizt ist.", image: "Semmel"),
        Recipe(id: "2",title:"Granola Bowl mit Kokos", subtitle: "Nach Lust und Laune mit Obst servieren.", category: "Amerikanisch", time: "10 Min.", description: "Eine halbe Banane und die Hälfte der Beeren mit dem Quark und etwas Wasser mischen und mit dem My Smoothie Extractor zu Brei verarbeiten. Diesen anschließend in eine Schale geben. Die restliche Banane und Beeren sowie die Kokosraspeln, Leinsamen, Granola und etwas Honig als Topping anrichten.", image: "Nudelteig"),
        Recipe(id: "3",title:"Pekanuss-Schokokuchen", subtitle: "Leicht und schnell selbstgemacht", category: "Amerikanisch", time: "55 Min.", description: "200 g Zartbitterschokolade und 100 g Vollmilchschokolade grob hacken und mit 110 g Butter über einem heißen Wasserbad schmelzen. Drei Teelöffel Crème fraîche unterrühren. Währenddessen eine Backform oder ein kleines tiefes Backblech mit Backpapier auslegen. 130 g Pekannüsse grob hacken. Drei Eier mit 100 g Zucker und einem halben Teelöffel Salz in einer Schüssel hell cremig aufschlagen, bis sich der Zucker gelöst hat. Nach und nach die abgekühlte Schokolade unter den Eier-Mix rühren. 180 g Mehl mit Nüssen und 10 g Backpulver mischen und ebenfalls unterrühren. Teig in die Backform füllen und glatt streichen. Kuchen im vorgeheizten Backofen bei 180 °C (Umluft 160 °C; Gas: Stufe 2–3) etwa 25–30 Minuten backen - er sollen in der Mitte noch etwas weich sein, so dass bei der Stäbchenprobe noch ein wenig Teig kleben bleiben darf. Abkühlen lassen und in Stücke (ca. 5 x 6 cm) schneiden.", image: "Tempeh"),
        Recipe(id: "4",title:"Cinnamon Rolls", subtitle: "Einfach und lecker.", category: "Amerikanisch", time: "30 Min.", description: "220 ml Milch und 50 g Butter kurz erwärmen, bis die Butter geschmolzen ist. Zunächst 450 g Mehl, eine Prise Salz, 70 g Zucker und ein Ei in eine Schüssel geben. Eine Mulde in das Mehl drücken und die Hefe hineinbröseln. Die Mich hineingießen und alles von der Mulde aus nach außen zu einem glatten Teig verkneten. Wenn der Teig noch zu klebrig ist, nach und nach nur so viel Mehl hinzugeben, bis er sich gut verarbeiten lässt. Zugedeckt an einem warmen Ort 1 Stunde gehen lassen. Den Teig rechteckig ausrollen und mit der Butter bestreichen. Zucker und Zimt mischen und darüber streuen, keinen Rand lassen. Von der langen Seite her aufrollen und in 2 - 3 cm dicke Scheiben schneiden. Mit der Schnittfläche nach unten in eine gefettete Form (z.B. eine Auflaufform) setzen und zugedeckt weitere 30 Minuten gehen lassen. Für die Glausur 100 g Frischkäse, 30 g Butter und 100 g Puderzucker mit vier Trocken Vanillearoma verrühren. Wenn sie etwas zu dicklich erscheint, ein wenig Milch hinzugeben - sie sollte aber auf keinen Fall zu flüssig werden. Natürlich kann man nach Belieben auch eine normale Glasur aus Milch und Puderzucker zubereiten, diese hier verleiht dem Rezept aber einen besonderen Kick. Die Rollen im vorgeheizten Backofen bei 180 °C Ober-/Unterhitze ca. 15 - 20 backen.", image: "CinnaminRolls"),
        Recipe(id: "5",title:"Frühstücks-Quiche", subtitle: "Ein klassiker zum Frühstück.", category: "Französisch", time: "75 Min.", description: "Für den Boden 150 g Kartoffeln schälen, waschen, trocken tupfen und grob raspeln. Kartoffeln,  15 g Mehl, ein Ei gut vermengen, mit Salz, Pfeffer und Muskat würzen. Eine Tarteform (24 cm Ø) fetten und mit Mehl ausstäuben. Kartoffelmasse in die Form geben und als Boden und Rand andrücken, dabei den Rand etwas höher drücken als der Formrand. Im vorgeheizten Backofen auf unterster Schiene ca. 15 Minuten backen. Inzwischen Zwiebel schälen und fein würfeln. Champignons putzen, säubern und vierteln. Zucchini waschen, putzen, trocken reiben und grob raspeln. Öl in einer Pfanne erhitzen, Champignons darin unter Wenden kräftig anbraten. Zwiebel und Zucchini zufügen, kurz mit anbraten. Mit Salz und Pfeffer würzen. Schinken untermengen. Käse fein reiben. Für den Guss Sahne und drei Eier verquirlen. Mit Salz, Pfeffer und Muskat abschmecken. Boden aus dem Ofen nehmen, Champignon-Zucchini-Schinkenmischung gleichmäßig darauf verteilen. Guss gleichmäßig darübergießen. Mit Käse bestreuen und bei gleicher Temperatur ebenfalls auf unterster Schiene ca. 30 Minuten backen. Majoran waschen, trocken schütteln, Blättchen von den Stielen zupfen. Quiche aus dem Ofen nehmen, ca. 10 Minuten ruhen lassen. Vorsichtig aus der Form lösen und mit Majoran bestreut auf einer Platte anrichten.", image: "Tarte"),
        Recipe(id: "6",title:"Pochierte Eier auf Brot", subtitle: "Serviert mit Räucherlachs und Holandaise", category: "Französisch", time: "30 Min.", description: "In einem großen Topf Wasser erhitzen. Die Eier in einer Metallschüssel aufschlagen. Die Schüssel sollte in den Topf passen. Das Wasser sollte die Schüssel nicht berühren die Butter in der Mikrowelle kurz schmelzen, dass sie flüssig ist. Sie sollte lauwarm sein. Die Schüssel in den Topf stellen und die Flamme klein stellen. Nun die Eier mit dem Schneebesen schaumig rühren und das Salz zugeben. Die Hollandaise Sauce gut mit dem Schneebesen wie bei einer Zabaione rühren und nicht aufhören. Ganz langsam die flüssige Butter zu dem Eigelb geben und mit dem Senf und dem Zitronensaft aufschlagen bis sie eindickt. Die Eier einzeln in einer Schüssel aufschlagen und vorsichtig in das siedende aber nicht kochende Wasser gleiten lassen. Mit einem Löffel vorsichtig das Eiweiß um das Eigelb drehen. Die Eier im Essigwasser ca. vier Minuten pochieren. Auf eine getoastete Scheibe Brot der Rächerlachs legen. Die pochierten Eier mit einem Schöpflöffel entnehmen und zum Abtropfen auf Küchenpapier geben. Dann auf das Brot setzen und mit einem Löffel etwas Hollandaise darauf verteilen.", image: "EggBenedict"),
        Recipe(id: "7",title:"Bauernfrühstück mit Spiegelei", subtitle: "Deftiges Frühstück", category: "Deutsch", time: "45 Min.", description: " 700 g Kartoffeln ungeschält in einem großen Topf Salzwasser garen lassen. Anschließend mit kaltem Wasser abschrecken, abtropfen, pellen und auskühlen lassen. Danach in ca. ein Zentimeter dicke Scheiben schneiden. Vier Zwiebeln abziehen und in halbe Ringe schneiden. Sparte vom Speck entfernen und 100 g Speck grob würfeln. Speck in einer Pfanne zerlassen. Sobald genügend Fett ausgetreten ist, 400 g Rindergulasch hinzufügen und beides durchbraten. Fleisch aus der Pfanne nehmen. Butterschmalz zerlassen und Kartoffelscheiben in der Pfanne auslegen. Fünf Minuten anbraten lassen, dann Kartoffeln wenden. Zwiebeln sowie Fleisch-Speck-Mischung dazugeben. Auf mittlerer Hitze zehn Minuten braten lassen und mit Salz und Pfeffer abschmecken. In einer separaten Pfanne Olivenöl erhitzen und vier Spiegeleier braten. Bauernfrühstück auf vier Tellern anrichten und mit je einem Spiegelei belegen. Frische Petersilie darüber streuen.", image: "Bratkartoffeln"),
        Recipe(id: "8",title:"Burger mit Laugenbrötchen udn Spiegelei", subtitle: "Burger mal anders", category: "Deutsch", time: "30 Min.", description: "Den Backofen vorheizen. Tomaten und Essiggurken in dünne Scheiben schneiden. Die Zwiebel schälen und in Ringe schneiden. Die Semmeln quer halbieren und im Ofen (Mitte) 5 Minuten rösten. Etwas Öl in zwei Pfannen erhitzen. In einer Pfanne die Burgerpatties von beiden Seiten in 10 Minuten braun braten. Die Eier in die zweite Pfanne aufschlagen und bei schwacher Hitze 2–3 Minuten stocken ­lassen. Dann wenden und die Spiegeleier von der zweiten Seite ebenfalls 2–3 Minuten braten. Mit Salz und Pfeffer würzen. Die Schnittflächen der Semmeln mit Senf bestreichen und die Salatblätter darauf verteilen. Auf die Böden jeweils ein Patty, ein Spiegelei, Tomaten, Gurken und Zwiebelringe schichten. Wer möchte kann auch zusätzlich noch Bacon anbraten und diesen auf den Burger legen. Die Deckel auflegen und mit Holzstäbchen fixieren.", image: "Laugen"),
        Recipe(id: "9",title:"Weißwürste mit süßem Senf und Brezeln", subtitle: "Schmeckt nicht nur in Bayern", category: "Deutsch", time: "20 Min.", description: "Einen großen Topf mit Wasser füllen und zum Kochen bringen. Die Hitze abschalten und die Weißwürste hineingeben. Zugedeckt ca. 10 Minuten ziehen lassen. Weißwürste nicht kochen lassen, sonst können sie platzen! Die Weißwürste in heißem Wasser (Topf oder Suppenterrine) servieren. Dazu Senf und Laugenbrezeln reichen. Und natürlich ein Weißbier mit oder ohne Alkohol.", image: "Weiswurst"),
        Recipe(id: "10",title:"Rührei", subtitle: "Einfach und lecker", category: "Deutsch", time: "10 Min.", description: "Eier aufschlagen und mit Milch verquirlen. Mit Salz würzen. Die Margarine in einer Pfanne scmelzen. Danach die Eiermischung auf einmal in die Pfanne gießen und einen Moment braten. Mit einem Küchenfreund das Ei von außen nach innen schieben. Zum Schluss den Schnittlauch darüber schneiden.", image: "Ei"),
        Recipe(id: "11",title:"Croissants", subtitle: "Selbstgebacken", category: "Französisch", time: "300 Min.", description: "Ca. 1 Stunde vor Beginn, 25 g Hefe und 250 g Butter bei Zimmertemperatur aufwärmen lassen. 500 g Mehl mit Salz vermischen. 200g Wasser, 125 g Milch und 40 g Zucker in der Mikrowelle erwärmen (Trinktemperatur). Danach die Hefe darin auflösen. Eine Vertiefung ins Mehl drücken und die Flüssigkeit unter Rühren langsam dazuschütten. Das Mehl von innen nach außen unterarbeiten, bis eine Teigkugel entsteht. Schüssel zudecken und den Teig 30 Minuten gehen lassen. Währenddessen 250g weiche Butter mit 50g Mehl verrühren. Nach 30 Minuten: Teig noch einmal durchkneten, dann aus der Schüssel nehmen und in 4 Kugeln teilen. Butter ebenfalls in 4 gleiche Portionen aufteilen. Ein Arbeitsbrett gut einmehlen und eine Teigportion darauf ausrollen - sollte ca. DIN A4-Größe ergeben - Zwischendurch immer wieder wenden und neu einmehlen. Eine Portion Butter in die Mitte setzen und auf ca. Postkartengröße grob verstreichen. Danach die verstrichene Butter in den Teig einpacken. Dazu den Teig sehr leicht anfeuchten und zuerst die langen Kanten umschlagen und danach die kurzen Seiten übereinanderschlagen. Das verhindert, daß die Butter in den folgenden Arbeitsschritten aus dem Teig tritt. Das Teigpäckchen in Frischhaltefolie einwickeln und in den Kühlschrank verfrachten. Dasselbe für die anderen Portionen wiederholen. Der Teig muss mindestens(!) 4 Stunden im Kühlschrank bleiben. Vier Stunden ruhen lassen. Arbeitsplatte gut einmehlen, eine Portion Teig aus dem Kühlschrank holen und in eine längliche Form ausrollen.", image: "Croissant")
    ]
}
