//
//  Data.swift
//  Rezepte
//
//  Created by Natalie Wolf on 26.09.20.
//

struct Recipe: Hashable{
    let title: String
    let subtitle: String
    let category: String
    let time: String
    let description: String
    let image: String
    var favourited: Bool
}

let recipes = [
    Recipe(title:"Veganes Bananenbrot", subtitle: "Simples Bananenbrot mit Walnüssen", category: "Deutsch", time: "1 Std.", description: "Den Ofen auf 180°C Umluft vorheizen.Das Dinkelmehl, Backpulver und Salz in einer großen Schüssel vermischen.In einer zweiten Schüssel zwei geschälte Bananen mit einer Gabel zerdrücken, sodass ein Brei entsteht.Das Apfelmus und die pflanzliche Milch zu dem Bananenbrei hinzugeben und gut verrühren.Die feuchten Zutaten nun nach und nach zu dem Mehl geben, sodass eine homogene Masse entsteht.Die Walnüsse grob hacken und 100 g der Walnüsse gemeinsam mit den Schokoladentropfen unterrühren. 50 g der gehackten Walnüsse bei Seite legen.Eine Kastenform (11x25 cm) mit 1 EL pflanzlicher Butter einfetten und mit 1 EL Dinkelmehl ausklopfen.Den Teig in die Kastenform geben. Die letzten 50 g der Walnüsse auf dem Teig verteilen.Das Bananenbrot bei 180°C Umluft auf mittlerer Schiene etwa 60 Minuten backen. Nach etwa 30-40 Minuten mit Folie abdecken, damit die Walnüsse nicht verbrennen. Nach dem Backen abkühlen lassen und in 12 Stücke teilen.", image: "Bananenbrot", favourited: false),
    Recipe(title:"Semmelknödel", subtitle: "Herzhafter Klassiker", category: "Deutsch", time: "80 Min.", description: "Brötchen in etwa 1 cm große Stücke schneiden. Mit 275 ml Sojadrink übergießen und kurz verrühren.Den restlichen Sojadrink mit Sojamehl glatt rühren und mit Salz und Muskat würzen. Unter die Brötchenmasse heben und gut vermengen. Zwiebel fein würfeln, Petersilie hacken. Öl in eine heiße Pfanne geben, Zwiebelwürfel bei niedriger bis mittlerer Hitze 5 Minuten anbraten, bis sie leicht gebräunt sind. Petersilie dazugeben, unter Rühren weitere 2 Minuten rösten. Anschließend zusammen mit Semmelbröseln und Kartoffelstärke zur Knödelmasse geben, gut durchkneten und anschließend abgedeckt 10 Minuten quellen lassen. Mit trockenen Händen 8 Knödel formen und reichlich Salzwasser sanft zum Kochen bringen. Hitze auf niedrige Stufe stellen – das Wasser sollte nicht mehr kochen – und die Knödel 15-20 Minuten sieden lassen, bis sie an der Oberfläche schwimmen.", image: "Semmel", favourited: false),
    Recipe(title:"Nudelteig", subtitle: "Selbstgemacht und vegan", category: "Deutsch", time: "45 Min.", description: "Weizenmehl, Hartweizengries und Salz grob vermengen. Auf die Arbeitsfläche geben und eine Kuhle in der Mitte bilden. Olivenöl und 175 ml lauwarmes Wasser hineingeben und mit einer Gabel von der Mitte aus vermengen, bis ein bröseliger Teig entstanden ist. Anschließend in der Küchenmaschine oder von Hand 10 Minuten zu einem glatten Teig verkneten. Bei Bedarf esslöffelweise Wasser hinzugeben. In einen luftdicht verschließbaren Behälter geben und 20 Minuten im Kühlschrank ruhen lassen. Nudelmaschine vorbereiten. Dazu die Walzen leicht mit Mehl bestäuben. Teig in 6-8 gleich große Stücke teilen. Jeweils zu Kugeln formen. Jeweils einen Teigling bei größtem Walzenabstand durch die Nudelmaschine führen. Teig von den beiden langen Seiten her zur Mitte falten, sodass ein Rechteck entsteht. Weitere zwei mal bei größtem Walzenabstand durch die Maschine laufen lassen, dann die Stufen nach und nach reduzieren, bis der Teig etwa 1/2 Millimeter dick ist. Fertig ausgerollte Nudelplatten unter einem leicht angefeuchteten Tuch lagern und nicht übereinanderstapeln. Die Platten können jetzt von Hand oder mit der Maschine zu Spaghetti, Fettuccine oder Pappardelle geschnitten und gleich gekocht, getrocknet oder eingefroren werden. Dazu vor und nach dem Schneiden leicht mit Mehl bestäuben.", image: "Nudelteig", favourited: false),
    Recipe(title:"Tempeh", subtitle: "Leicht selbstgemacht", category: "Deutsch", time: "1 Std.", description: "Sojabohnen in der vierfachen Menge Wasser aufkochen und anschließend bei mittlerer Hitze 45-60 Minuten köcheln lassen, bis sie gar sind und noch einen leichten Biss haben.Bohnen abgießen und gut abtropfen lassen. Zurück in den Topf geben und auf die noch heiße Herdplatte stellen. Ab und zu umrühren, bis die überschüssige Feuchtigkeit verdampft ist.Essig unterrühren und die Bohnen auf 32 °C abkühlen lassen. Anschließend die Tempeh-Kultur unterrühren. Reifebehälter vorbereiten. Dazu zum Beispiel Frischhaltebeutel mit etwa 1 l Fassungsvermögen verwenden und flächendeckend alle 2 cm Löcher hineinpiksen. Etwa bis zur Hälfte mit Bohnen füllen, zu kompakten Laibern formen und die Beutel durch strammes Umfalten verschließen. Bei 30-34 °C für 24-48 Stunden reifen lassen, bis der Tempeh gleichmäßig mit dem weißen Pilz überzogen ist. Wir verwenden dazu den Backofen mit angeschaltetem Licht und eine Wärmflasche, die etwa alle 12 Stunden frisch mit heißem Wasser befüllt wird. Die Ofentür wird mit Hilfe eines Essstäbchens einen Spalt offen gelassen.", image: "Tempeh", favourited: false),
    Recipe(title:"Hummus", subtitle: "Basic Rezept", category: "Amerikanisch", time: "15 Min.", description: "Kichererbsen, Knoblauch, Tahin, Zitronensaft und Salz in eine Küchenmaschine oder einen Mixer geben und glattpürieren. Bei Bedarf etwas Wasser hinzugeben.Hummus mit Olivenöl, Sesam, Granatapfelkernen, fein geschnittenen Zwiebeln und frischen Minzblättern toppen.", image: "Hummus", favourited: false),
    Recipe(title:"Fladenbrot", subtitle: "Ein klassiker", category: "Amerikanisch", time: "1 Std.", description: "Mehl, Hefe, Sojaquark, 2 EL Olivenöl und Salz zusammen mit 75 ml lauwarmen Wasser vermengen und mit der Küchenmaschine 10 Minuten zu einem glatten Teig verkneten. Abgedeckt an einem warmen Ort 30 Minuten gehen lassen, bis sich das Volumen in etwa verdoppelt hat.Teig vierteln, rund formen und die Teiglinge mit dem restlichen Olivenöl einstreichen. Zunächst mit den Händen rund formen und dann auf etwa 26 cm Durchmesser ausrollen. Die Arbeitsfläche musst du nicht bemehlen, der Ölfilm sorgt dafür, dass nichts anklebt. Optional mit Sesam und Schwarzkümmel bestreuen und die Körner leicht andrücken.", image: "Fladenbrot", favourited: false),
    Recipe(title:"Gefüllte Muschelnudeln mit Räuchertofu & Spinat", subtitle: "perfektes Dinner", category: "Amerikanisch", time: "2 Std.", description: "Conchiglioni 10 Minuten in Salzwasser garen. Anschließend aus dem Pastawasser nehmen und gut abtropfen lassen. Backofen auf 180 °C Ober-/Unterhitze vorheizen. Spinat im noch heißen Pastawasser 1 Minuten blanchieren, anschließend abgießen, gut abtropfen lassen und auspressen. Für die Sauce Zwiebel würfeln, Knoblauch in Scheiben schneiden. Öl in einen heißen Topf geben, Zwiebel und Knoblauch bei mittlerer Hitze 2 Minuten andünsten. Mit Salz, Chiliflocken und Fenchelsamen würzen, Knoblauch dazugeben und weitere 3 Minuten dünsten. Tomatenmark und Ahornsirup unterrühren und 3 Minuten karamellisieren lassen. Mit gehackten Tomaten und 200 ml Wasser ablöschen, kurz aufkochen und 5 Minuten köcheln lassen. Für die Füllung Räuchertofu und Frischkäse im Foodprocessor fein pürieren oder mit einem Kartoffelstampfer stampfen. Mit Salz, Pfeffer und Zitronenzesten abschmecken, Spinat fein hacken und unterheben und beiseite stellen. Sauce auf dem Boden einer Auflaufform verteilen, Conchiglie mit der Füllung befüllen, auf der Sauce verteilen, mit Reibekäse toppen und 30 Minuten überbacken. Mit frisch gezupftem Basilikum getoppt servieren", image: "Muschelnudeln", favourited: false),
    Recipe(title:"Kürbispizza mit Radicchio und Granatapfel", subtitle: "Hrebstlich", category: "Amerikanisch", time: "30 Min.", description: "Pizzastein auf ein Backgitter legen, Backofen auf höchster Stufe vorheizen und den Stein weitere 30 Minuten aufheizen lassen.Je eine Teigportion vorsichtig rund auf etwa 16-20 cm Durchmesser ziehen oder ausrollen. Mit je 3-4 EL Sauce bestreichen, mit Kürbis, Radicchio und Zwiebel belegen. 1 EL Polenta auf dem Stein verteilen, Pizza auf den heißen Pizzastein legen. Kürbispizza 7-8 Minuten backen.", image: "Kürbispizza", favourited: false),
    Recipe(title:"Apfelkuchen mit Streuseln", subtitle: "Wie bei Oma", category: "Französisch", time: "75 Min.", description: "Für den Mürbteig Mehl, Erythrit, kalte vegane Butterstückchen und Salz rasch zu einem krümeligen Teig vermengen. Anschließend zu einer Kugel formen und bis zur Weiterverarbeitung abgedeckt im Kühlschrank aufbewahren. Äpfel schälen, vierteln und entkernen. Anschließend in 3 mm dünne Scheiben schneiden und mit Zitronensaft vermengen. Vanille, Zimt und Sultaninen hinzufügen und unterheben. Backofen auf 180 °C Ober-/Unterhitze vorheizen. Springformboden (24 cm Durchmesser) mit Backpapier auskleiden, Rand einfetten. Mürbteig in die Springform geben, verteilen und gleichmäßig flachdrücken. Dabei einen etwa 2 cm hohen Rand bilden. Das geht am besten mit der Rückseite eines Löffels. Apfelmischung auf dem Kuchenboden verteilen. Für die Streusel alle Zutaten mit einer Gabel oder den Händen vermengen und zu groben Streuseln verarbeiten. Kuchen gleichmäßig damit toppen. Auf mittlerer Schiene 40-45 Minuten Backen. Kuchen kurz abkühlen lassen und aus der Springform lösen. Lauwarm oder kalt servieren.", image: "Apfelkuchen", favourited: false),
    Recipe(title:"Saftige Lebkuchenriegel", subtitle: "Mit Datteln & Tonkabohne", category: "Französisch", time: "25 Min.", description: "Datteln, Nüsse und Gewürze zusammen mit etwa 50 ml Wasser pürieren, bis eine gleichmäßige, nicht zu trockene Masse entstanden ist. Masse auf 2 Oblaten verteilen und gleichmäßig auf etwa 1 cm Dicke verstreichen. Mit den übrigen Oblaten abdecken, gut andrücken und 10 Minuten im Tiefkühlfach kühlen. Anschließend in 10 Riegel schneiden", image: "Lebkuchenriegel", favourited: false),
    Recipe(title:"Schokoladen-Babka", subtitle: "Saftig lecker", category: "Französisch", time: "2 STd.", description: "Zucker in lauwarmen Haferdrink auflösen. Zusammen mit Salz, Vanille, Hefe und Öl zum Mehl geben und 10 Minuten zu einem gleichmäßigen Teig verkneten. Mit einem Deckel abgedeckt an einem warmen Ort 1 Stunde gehen lassen, bis sich das Teigvolumen verdoppelt hat. FÜR DIE FÜLLUNG:Schokolade, zusammen mit dem Mandelmus, in einem Wasserbad vorsichtig schmelzen. Kakaopulver unterrühren. Teig auf einer gut bemehlten Arbeitsfläche dünn auf etwa 25 x 40 cm ausrollen, mit der Schokoladenfüllung bestreichen und von der langen Seite her aufrollen. Mit einem scharfen Messer längs halbieren und die beiden Hälften abwechselnd vorsichtig übereinander legen. Kastenform mit Backpapier auslegen, Babka vorsichtig hineingeben und abgedeckt an einem warmen Ort weitere 30 Minuten gehen lassen. Backofen auf 190 °C Ober-/Unterhitze vorheizen. Babka 35 Minuten backen, anschließend mit etwas Ahornsirup bestreichen und vor dem Anschneiden vollständig abkühlen lassen.", image: "Babka", favourited: false),
    Recipe(title:"Chocolate Chip Cookies", subtitle: "Ultrakaramelliger American Dream Cookie", category: "Französisch", time: "60 Min.", description: "Mehl, Backpulver, Natron und Salz vermengen. Zartbitterschokolade grob hacken und zusammen mit den Schokotröpfchen zur Mehlmischung geben. In einer zweiten Schüssel Zucker, Öl, Vanilleextrakt und 60 ml Wasser verrühren bis eine homogene Masse entstanden ist. Die Mehlmischung nach und nach zur Zuckermischung geben und mit einem Löffel rasch unterheben, bis alles gut vermengt ist. In einen verschließbaren Container füllen und für mindestens 12 Stunden im Kühlschrank ruhen lassen. Den kalten Cookie Dough locker mit einem Eisportionierer in 14 Kugeln formen und mit genügend Abstand auf ein mit Backpapier ausgelegtes Backblech geben. Anschließend für 15 Minuten im Gefrierfach ruhen lassen. Backofen auf 175 °C Ober-/Unterhitze vorheizen. Cookies auf mittlerer Schiene etwa 12-13 Minuten backen und noch heiß sparsam mit Salzflocken bestreuen. Vor dem Servieren komplett abkühlen lassen.", image: "Cookies", favourited: false),
    Recipe(title:"Kürbispizza mit Radicchio und Granatapfel", subtitle: "Hrebstlich", category: "Französisch", time: "30 Min.", description: "Pizzastein auf ein Backgitter legen, Backofen auf höchster Stufe vorheizen und den Stein weitere 30 Minuten aufheizen lassen.Je eine Teigportion vorsichtig rund auf etwa 16-20 cm Durchmesser ziehen oder ausrollen. Mit je 3-4 EL Sauce bestreichen, mit Kürbis, Radicchio und Zwiebel belegen. 1 EL Polenta auf dem Stein verteilen, Pizza auf den heißen Pizzastein legen. Kürbispizza 7-8 Minuten backen.", image: "Kürbispizza", favourited: false),
]



